"""first try

Revision ID: 0bbd8b72c27d
Revises: 
Create Date: 2021-05-17 14:29:32.703254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bbd8b72c27d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('black_cards', sa.Column('source', sa.String(), nullable=True))
    op.add_column('decks', sa.Column('source', sa.String(), nullable=True))
    op.add_column('white_cards', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('white_cards', 'source')
    op.drop_column('decks', 'source')
    op.drop_column('black_cards', 'source')
    # ### end Alembic commands ###
